name: CI/CD Pipeline to Azure

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install pytest

      - name: Test with pytest
        run: cd backend && pytest test.py

  build-and-deploy:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure ACR Login
        run: az acr login --name aminab15

      - name: Build and Push Docker Images
        run: |
          docker build -t portfoliofront -f frontend/Dockerfile frontend 
          docker build -t portfolioback -f backend/Dockerfile backend 
          docker tag portfoliofront:latest aminab15.azurecr.io/portfoliofront:latest
          docker tag portfolioback:latest aminab15.azurecr.io/portfolioback:latest
          docker push aminab15.azurecr.io/portfolioback:latest
          docker push aminab15.azurecr.io/portfoliofront:latest

          - name: Deploy to Azure Container Instances
          uses: azure/CLI@v1
          with:
            azcliversion: latest
            inlineScript: |
              az container delete --name aminab09-back --resource-group gr_aminab15 --yes
              az container create --resource-group gr_aminab15 --name aminab09-back \
                --image aminab15.azurecr.io/portfolioback:latest \
                --cpu 1 --memory 1 \
                --ports 8000 \
                --dns-name-label portfolioaminaback \
                --registry-login-server aminab15.azurecr.io \
                --registry-username aminab15 \
                --registry-password ${{ secrets.AZURE_REGISTRY }}

              set -e  # Stop script execution on any error
              az container delete --name aminab09-front --resource-group gr_aminab15 --yes
              az container create --resource-group gr_aminab15 --name aminab09-front \
                --image aminab15.azurecr.io/portfoliofront:latest \
                --cpu 1 --memory 1 \
                --ports 8001 \
                --dns-name-label portfolioaminafront \
                --registry-login-server aminab15.azurecr.io \
                --registry-username aminab15 \
                --registry-password ${{ secrets.AZURE_REGISTRY }}


